# Generated by Django 4.2.4 on 2023-08-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('preparing', 'Preparing'), ('completed', 'Completed')], default='received', max_length=20)),
                ('dishes', models.ManyToManyField(to='zomato_app.dish')),
            ],
        ),
    ]
